name: build docs

on:
  push:
    branches:
      - gh_actions

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
            python3 -m pip install --upgrade pip
            python3 -m pip install -r requirements-dev.txt

      - name: Build docs
        run:  invoke docs-build -f

